# Generated by Django 5.1.1 on 2024-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
