# Generated by Django 5.1.1 on 2024-09-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_item_completed_at_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
    ]
